import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Password Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children } : { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-svh flex justify-center items-center font-mono text-sm lg:flex`}>
        <div className="w-[22rem] px-4 py-4 flex h-svh flex-col items-center justify-between bg-[#EAD1D1]">
          {children}
        </div>
      </body>
    </html>
  );
}
